### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by DusanSacha** [react-puzzle-games/15-puzzle#15]
It would be nice to have the same footer like in the other games.

**Comment by DusanSacha** [comment]
@ovidiubute , would you go for a footer like this?

![react_puzzle04](https://user-images.githubusercontent.com/16412025/27082645-e3225d64-5045-11e7-810c-4f8bc18d6f36.png)

**Comment by ovidiubute** [comment]
Looking good 😃  Maybe remove the text-decoration from the link and try a different color? I'm thinking it should somehow match the rest of the app. Maybe try reusing the tile color and see how it looks.

**Comment by DusanSacha** [comment]
Thanks! Nice idea! I think it looks better now. (changed the heart and link color to match the tiles + background color set to the same color as in the header)
![react_puzzle05](https://user-images.githubusercontent.com/16412025/27120508-2b27ed60-50e4-11e7-8167-24058c08f39b.png)

**Comment by ovidiu-bute-hs** [comment]
LGTM 👍

**Comment by ovidiu-bute-hs** [comment]
Make sure you check how it looks on a mobile device too just in case there are weird issues.

**Comment by DusanSacha** [comment]
Yes, I was checking that. Currently thinking how to position the footer to the bottom. Because with `position:absolute; bottom: 0px;` it can render weird on mobile landscape display. Will check some more-flex solution. 

![react_puzzle06](https://user-images.githubusercontent.com/16412025/27121596-42986516-50e8-11e7-85df-c9d05e317048.png)

**Comment by DusanSacha** [comment]
Implemented in PR #40
