### ISSUE TITLE
Implement number of moves counter

### ISSUE THREAD

**Issue by ovidiubute** [react-puzzle-games/15-puzzle#2]

**Comment by DusanSacha** [comment]
Hi, I am interested in joining your react-puzzle-games projects. Are you open for contributions?
Didn't find any contact information, so I tried it this way. Let me know. Thanks!

**Comment by ovidiubute** [comment]
Hi! We're absolutely accepting contributions! 

There are no guidelines as of yet but you can check out the issues on any of the projects inside the organisation to get familiar with where we're at with the projects. We also have a more long-term [roadmap](https://github.com/orgs/react-puzzle-games/projects) if you'd like to check out. 

15-puzzle, in particular, is probably the best project to start on as it is missing some pretty important things like the end game logic. The other two games are done but could benefit from a nicer UI and some UX improvements.

**Comment by DusanSacha** [comment]
Thanks! I will check the projects out. Just the roadmap link leads to a 404 page.

**Comment by ovidiubute** [comment]
I think you need to accept my invitation to join the organization first, check your GitHub notifications tab or your e-mail.

**Comment by DusanSacha** [comment]
Thanks. I have [created a PR](https://github.com/react-puzzle-games/15-puzzle/pull/14) for this issue.

**Comment by ovidiubute** [comment]
Fixed in #14
