### ISSUE TITLE
Warn user about refreshing the game during a game

### ISSUE THREAD

**Issue by ovidiubute** [react-puzzle-games/15-puzzle#24]
This is a nice way to prevent accidentally losing your progress, just have an alert on page reload *only if* a game is currently underway.

Not sure how it'll look on mobile, though, need to try it out and see how it feels.

**Comment by DusanSacha** [comment]
Can you be more specific here?

Do you want to prevent the page refresh? Show some Popup "OK x Cancel" dialog -  before the refresh?

**Comment by ovidiubute** [comment]
I see a JavaScript `alert` warning the user he's going to lose all of his game progress. Think of `inbox` or `google docs`. But only if you start the game and don't finish it, otherwise it's intrusive :)

**Comment by ovidiubute** [comment]
Although maybe a modal is better than an `alert` since `alert` blocks the tab completely...

**Comment by DusanSacha** [comment]
I was thinking about using [Snackbar](http://www.material-ui.com/#/components/snackbar) for the warning. With a message like "Please, be aware that by refreshing the page (hitting F5) all your current progress will be lost." (button Hide).

What do ya think? I am going to post a screenshot tomorrow.

**Comment by ovidiubute** [comment]
I'm not sure what the UX would be like, usually that component is used for notifications that show up and can then be dismissed or dismiss themselves after a period of time. This issue is more of a corner case to be honest, maybe we shouldn't even think about it and instead persist the user's progress to offline LocalStorage and then we won't even have this problem. 

We can use the Snackbar for example for when a user clicks a (not yet in UI) Pause button. You'd get a persistent notification "The game is currently paused". Then if he unpauses you get another Snackbar and it says "Game on!" or something, and goes away.

**Comment by DusanSacha** [comment]
Hmm, I guess you are right with the use case for the Snackbar... so would you close this issue for now?

**Comment by ovidiubute** [comment]
Will open a LocalStorage issue instead of doing this.
