### ISSUE TITLE
Implement material-ui design

### ISSUE THREAD

**Issue by ovidiubute** [react-puzzle-games/15-puzzle#25]
The buttons and messages could do with a Material UI overhaul. The nice part about using it is it's already great on mobile devices so no need to spend a lot of effort on that front. 

Will need a mockup though before starting work.

**Comment by DusanSacha** [comment]
Do you think, there is any Material UI Component which could be used for solving #24 ?

**Comment by ovidiubute** [comment]
Yup, a [Dialog](http://www.material-ui.com/#/components/dialog). This does involve adding `material-ui` to the project, but it's fairly simple.

**Comment by DusanSacha** [comment]
I am sending two screenshots how it could be done. Let me know what do you think ;)

![01](https://cloud.githubusercontent.com/assets/16412025/26287169/be6384d0-3e75-11e7-9538-61c4dd653b68.png)
![02](https://cloud.githubusercontent.com/assets/16412025/26287168/be5e4128-3e75-11e7-8add-b168f659868f.png)

**Comment by ovidiubute** [comment]
Looking good, man! I'd go with some different labels, though, let me know what you think:

> GITHUB LINK

Project home? 

> Contgratulations!

Congrats!
You solve the puzzle in ${moves} moves in ${formatted_time}!

**Comment by ovidiubute** [comment]
Maybe we could use some components to render the time and number of moves too, for example we could use [chips](http://www.material-ui.com/#/components/chip) each rendered with material UI icons like [this](https://material.io/icons/#ic_alarm) or [this](https://material.io/icons/#ic_compare_arrows) (finding just the right icons is arguably the hardest thing here 😄 ). Perhaps they could be part of a [toolbar](http://www.material-ui.com/#/components/toolbar)...

**Comment by DusanSacha** [comment]
I've tried to do a mockup. I think it is cool!

Maybe the buttons can be part of the toolbar as well. The question is then, how it would look like on mobile. Probably will collapse the title and the icontexts and in that case, buttons and icons could fit into the toolbar. 

What do you think? Buttons in the toolbar, or somewhere else?

![react_puzzle](https://cloud.githubusercontent.com/assets/16412025/26345756/3370d726-3fa4-11e7-9639-84993c90b097.png)

**Comment by DusanSacha** [comment]
I like the idea of toolbar...  so I was playing around more and I think it would look nice if we move everything to the toolbar and make it colapse on smaller devices:

![react_puzzle01](https://cloud.githubusercontent.com/assets/16412025/26360202/d5a71586-3fd7-11e7-8336-7a4d3a972af5.png)
![react_puzzle02](https://cloud.githubusercontent.com/assets/16412025/26360201/d4d76bce-3fd7-11e7-9198-8ad612e953e5.png)

It would need some more refactoring but it is doable :)
Lemme know what ya think

**Comment by ovidiubute** [comment]
Absolutely love it 👍  Works really good on mobile, too!

**Comment by DusanSacha** [comment]
That responsiveness is unfortunately not done automatically. I think I have to code it via media css queries.

**Comment by ovidiu-bute-hs** [comment]
Yeah I don't think an automated responsive UI framework exists, but it *should* be easy to handle with CSS media queries. `styled-components` supports this out of the box, you can take a look [at their docs](https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#more-powerful-example).

**Comment by DusanSacha** [comment]
Material UI was implemented - [PR](https://github.com/react-puzzle-games/15-puzzle/pull/31)
