### ISSUE TITLE
AirBnB linting

### ISSUE THREAD

**Issue by ovidiubute** [react-puzzle-games/15-puzzle#28]
- create-react-app linting is pretty lax
- AirBnB is superior so the project will benefit from it

**Comment by DusanSacha** [comment]
@ovidiubute Would you do it just by adding [this](https://www.npmjs.com/package/eslint-config-airbnb) package (and its dependencies) + changing the `"extends": "react-app"` to `"extends": "airbnb"` in `package.json`?
Or is there also something else behind this issue?

Thanks!

**Comment by ovidiu-bute-hs** [comment]
It should be enough, but then you also need to lint the code, which will involve some manual steps and could be a pretty big PR. Ideally we shouldn't have a lot of linting errors so maybe just try it out and see how many errors you get.

**Comment by DusanSacha** [comment]
Solved by PR #37
