### ISSUE TITLE
styled-components v2 upgrade

### ISSUE THREAD

**Issue by ovidiubute** [react-puzzle-games/15-puzzle#29]

**Comment by DusanSacha** [comment]
Are there any code changes needed in this one?

**Comment by ovidiu-bute-hs** [comment]
According to their site everything is backwards compatible, so we shouldn't need to change anything.

**Comment by DusanSacha** [comment]
OK, thanks for the info. I updated the dependency + snapshots.

**Comment by DusanSacha** [comment]
[PR 33](https://github.com/react-puzzle-games/15-puzzle/pull/33)

**Comment by ovidiubute** [comment]
Fixed in #33
