### ISSUE TITLE
Add Pause game button

### ISSUE THREAD

**Issue by DusanSacha** [react-puzzle-games/15-puzzle#34]

**Comment by ovidiubute** [comment]
I see this button as having two states: one where the game has started and it has a pause material icon and "Pause" text, and one where the game is paused, so the user already has clicked it, and it changes to render a continue material icon and the label is now "Continue". @DusanSacha what do you think?

**Comment by DusanSacha** [comment]
Yea, good idea and also using Snackbar as you mentioned earlier. I will just copy+pasted it here so we don't forget.

> We can use the Snackbar for example for when a user clicks a (not yet in UI) Pause button. You'd get a persistent notification "The game is currently paused". Then if he unpauses you get another Snackbar and it says "Game on!" or something, and goes away.

**Comment by ovidiubute** [comment]
Sounds cool to me 👍

**Comment by DusanSacha** [comment]
Before starting with the implementation...
I am thinking about where the pause button (and the new game button) will be located. Of course the first idea is - in the toolbar. However, on some smaller devices, when the toolbar buttons get collapsed, there is no more space for two other buttons. So maybe creating a footer and move "Project home" there would solve the problem?

**Comment by ovidiu-bute-hs** [comment]
I think moving the Project Home link to the footer makes perfect sense 👍

**Comment by ovidiu-bute-hs** [comment]
We can solve #18 too this way

**Comment by DusanSacha** [comment]
I tried to mock the Pause and New game buttons. As you said the biggest challenge is to pick [the right icon](https://material.io/icons/) for a new game 😄 
I think it looks good on desktop. For mobile I would tweak a bit the width to fit in.

Let me know what do you think.

![react_puzzle07](https://user-images.githubusercontent.com/16412025/27220795-b0c20ce6-5286-11e7-8b24-feb8ef109ff7.png)

![react_puzzle08](https://user-images.githubusercontent.com/16412025/27220796-b0c6b7f0-5286-11e7-9481-17a654774677.png)

Merci!

**Comment by ovidiubute** [comment]
Looks awesome 👍
